name: Deploy gh-pages
on: 
  push:
    branches: ["master"]
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: actions/checkout@v3
      run: echo Starting deploy...
      run: npm run deploy