name: Deploy gh-pages
on: 
  push:
    branches: ["master"]
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup packages
      run: npm install
    - name: Predeploy
      run: npm run predeploy
    - name: Deploy site
      run: npm run deploy